default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch( 'RAILS_MAX_THREADS' ){ 5 } %>
  host:  <%= ENV.fetch( 'DB_HOST' ){ 'db' } %>
  port: <%= ENV.fetch( 'DB_PORT' ){ 5432 } %>
  username: <%= ENV[ 'DB_USER' ] %>
  password: <%= ENV[ 'DB_PASSWORD' ] %>

development:
  <<: *default
  database: <%= ENV.fetch( 'DB_NAME' ){ 'pbs_development' } %>

test:
  <<: *default
  database: pbs_test

production:
  <<: *default
  database: <%= ENV.fetch( 'DB_NAME' ){ 'pbs_production' } %>
